language: bash

# Doc
# - Travis Job Lifecycle : https://docs.travis-ci.com/user/job-lifecycle/

matrix:
  include:
    - name: "Linux Debug"
      os: linux
      dist: focal
      env:
        - BUILD_NAME="linux-macos"
        - MODE=Debug

    - name: "MacOS Debug"
      os: osx
      osx_image: xcode12.2
      env:
        - BUILD_NAME="linux-macos"
        - MODE=Debug
      # too long installation
      #  - CC=/usr/local/opt/llvm/bin/clang-11
      #  - CXX=/usr/local/opt/llvm/bin/clang-11
      #addons:
      #  homebrew:
      #    # update: true
      #    packages:
      #      - llvm@11

    - name: "Windows Debug"
      os: windows
      env:
        - BUILD_NAME="windows"
        - MODE=Debug

install:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/install.sh

before_script:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/before_script.sh

script:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/build.sh
