# To debug a workflow see: https://docs.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging

name: C++ CI

on:
  push:
  schedule:
    - cron: '0 2 * * SAT'

jobs:
  build-unix:

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # seen at 20210531 in https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
          - name: Ubuntu GCC 11
            os: ubuntu-20.04
            c-compiler: gcc-11
            cxx-compiler: g++-11
          - name: Ubuntu GCC 11 Benchmark
            os: ubuntu-20.04
            c-compiler: gcc-11
            cxx-compiler: g++-11
            config: benchmark
          - name: Ubuntu GCC 10
            os: ubuntu-20.04
            c-compiler: gcc-10
            cxx-compiler: g++-10
          - name: Ubuntu GCC 9
            os: ubuntu-20.04
            c-compiler: gcc-9
            cxx-compiler: g++-9
          - name: Ubuntu Clang 13
            os: ubuntu-20.04
            c-compiler: clang-13
            cxx-compiler: clang++-13
          - name: Ubuntu Clang 12
            os: ubuntu-20.04
            c-compiler: clang-12
            cxx-compiler: clang++-12
          - name: Ubuntu Clang 12 Benchmark
            os: ubuntu-20.04
            c-compiler: clang-12
            cxx-compiler: clang++-12
            config: benchmark
          - name: Ubuntu Clang 11
            os: ubuntu-20.04
            c-compiler: clang-11
            cxx-compiler: clang++-11
          - name: Ubuntu Clang 10
            os: ubuntu-20.04
            c-compiler: clang-10
            cxx-compiler: clang++-10
          - name: macOS 10.15 Apple Clang
            os: macOS-10.15
          - name: macOS 10.15 Apple Clang Benchmark
            os: macOS-10.15
            config: benchmark
          # - name: macOS 10.15 Clang 12
          #  os: macOS-10.15
          #  c-compiler: clang-12
          #  cxx-compiler: clang++-12
          ## macOS-11 not yet publicly available
          # - name: macOS 11
          #   os: macOS-11
          #   compiler: # default

          # - name: NVidia HPC 20.11
          #   os: ubuntu-20.04
          #   c-compiler: nvc
          #   cxx-compiler: nvc++
          #   # for C++20 requires ≥21.1; check 
          #   # * https://ngc.nvidia.com/catalog/containers/nvidia:nvhpc
          #   # * https://developer.nvidia.com/nvidia-hpc-sdk-downloads
          #   container: nvcr.io/nvidia/nvhpc:21.5-devel-cuda_multi-ubuntu20.04  

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true
      # Usually already provided by GHA image (could be required in docker)
      # - name: install common
      #  run: |
      #     echo 'tzdata tzdata/Areas select Europe' | debconf-set-selections
      #     echo 'tzdata tzdata/Zones/Europe select Paris' | debconf-set-selections
      #     apt update && DEBIAN_FRONTEND="noninteractive" apt install -y tzdata
      #     apt install -y software-properties-common libpthread-stubs0-dev
      #     apt install -y curl sudo cmake ninja-build libtbb-dev
      - name: install Clang 13
        run: |
          # for sources, see https://apt.llvm.org
          curl -Ls https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
          sudo apt update && sudo apt install -qy clang-13 libc++-13-dev libc++abi-13-dev
        if: matrix.c-compiler == 'clang-13' && runner.os == 'Linux'
      - name: install Clang-12
        run: |
          # for sources, see https://apt.llvm.org
          curl -Ls https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main'
          sudo apt update && sudo apt install -qy clang-12 libc++-12-dev libc++abi-12-dev
        if: matrix.c-compiler == 'clang-12' && runner.os == 'Linux'
      - name: install Clang-11
        run: |
          sudo apt update && sudo apt install -qy clang-11 libc++-11-dev libc++abi-11-dev
        if: matrix.c-compiler == 'clang-11' && runner.os == 'Linux'
      - name: install GCC-11
        run: |
          sudo apt install -qy software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt install -qy gcc-11 g++-11
        if: matrix.c-compiler == 'gcc-11' && runner.os == 'Linux'
      - name: install locales
        run: |
          sudo apt install -y locales
          sudo locale-gen en_US fr_FR
          sudo update-locale en_US fr_FR
          # To verify installed rules:
          #     locale -a           # show all known locale
          #     export LC_ALL=fr_FR # select one locale
          #     locale -k LC_TIME   # show rule about with locale
        if: runner.os == 'Linux'
      - name: install additional tools and libs
        run: |
          if [ "${{runner.os}}" == "Linux" ]; then
            # libunwind-dev sometimes required to work around cxx_feature_check(STD_REGEX) for Google Benchmark 
            sudo apt install -y libtbb-dev ninja-build libunwind-dev
          fi
          if [ "${{runner.os}}" == "macOS" ]; then
            brew install tbb ninja
          fi
      - name: configure
        run: |
          echo "Configure on $(uname -a)"
          if [ "${{matrix.config}}" == "benchmark" ]; then
            mkdir build && cd build && CC="${{matrix.c-compiler}}" CXX="${{matrix.cxx-compiler}}" cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ONLY=TRUE 
          else
            mkdir build && cd build && CC="${{matrix.c-compiler}}" CXX="${{matrix.cxx-compiler}}" cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug
          fi
      - name: build
        run: cmake --build build
      - name: test
        run: |
          if [ "${{matrix.config}}" == "benchmark" ]; then
            cd build && ctest --timeout 200 --output-on-failure -V
          else
            cd build && ctest --timeout 200 --output-on-failure
          fi
      - name: show unsupported examples
        run: cat build/unsupported_examples.md 2>/dev/null || true

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-latest
          - name: Windows Benchmark
            os: windows-latest
            config: benchmark

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: configure
        shell: bash
        run: |
          if [ "${{matrix.config}}" == "benchmark" ]; then
            mkdir build && cd build && cmake -DBENCHMARK_ONLY=TRUE ..
          else
            mkdir build && cd build && cmake ..
          fi
      - name: build
        shell: bash
        run: |
          if [ "${{matrix.config}}" == "benchmark" ]; then
            cmake --build build --config Release
          else
            cmake --build build --config Debug
          fi
      - name: test
        shell: bash
        run: |
          if [ "${{matrix.config}}" == "benchmark" ]; then
            cd build && ctest -C Release --timeout 200 --output-on-failure -V
          else
            cd build && ctest -C Debug --timeout 200 --output-on-failure          
          fi
      - name: show unsupported examples
        shell: bash
        run: cat build/unsupported_examples.md 2>/dev/null || true
